# -*- coding: utf-8 -*-
"""WhatsApp_Message_Analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18RjmE6Lb5P3Lk6kwrxpYiw3P-5Ie_Z0p
"""

!python -m pip install regex

import re
import pandas as pd
import datetime

file = '/content/WhatsApp Chat with Munnar.txt'

with open(file, 'r') as f:
    ori_data = f.read()  # Reads the entire file content into a string

print(type(ori_data))  #hence proved

print(ori_data)

pattern = r'\d{1,2}\/\d{1,2}\/\d{2,4},\s\d{1,2}:\d{2}\s[AaPp][Mm]\s-\s'

data = ori_data.replace('\u202f', ' ')
pattern

# Fix: Use a valid variable name like 'messages'
messages = re.split(pattern, data)[1:]

# Now this line will work, giving you the number of items in the list
len(messages)



dates = re.findall(pattern, data)
dates

df = pd.DataFrame({'user_message': messages, 'message_date': dates})

df.head()

df['message_date'] = pd.to_datetime(df['message_date'], format='%d/%m/%y, %I:%M %p - ')

df.rename(columns={'message_date': 'date'}, inplace=True)

df.head()

df.shape

# Seperate users and messages
users = []
messages = []
for message in df['user_message']:
    entry = re.split(r'([\w\W]+?):\s', message)
    if entry[1:]:  # user name
        users.append(entry[1])
        messages.append(" ".join(entry[2:]))
    else:
        users.append('group_notification')
        messages.append(entry[0])

df['user'] = users
df['message'] = messages
df.drop(columns=['user_message'], inplace=True)

df.head()

# seperating and creating seperate coloums for all date,day,year,month
df['only_date'] = df['date'].dt.date
df['year'] = df['date'].dt.year
df['month_num'] = df['date'].dt.month
df['month'] = df['date'].dt.month_name()
df['day'] = df['date'].dt.day
df['day_name'] = df['date'].dt.day_name()
df['hour'] = df['date'].dt.hour
df['minute'] = df['date'].dt.minute

df.head()

